server:
  port: 8080

#是否开启 swagger-ui
swagger:
  enabled: true

#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farm_ilg?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

token:
  time: 60*60*24*7
  sign: PYCxxxxadsadsaAAAa

# 配置MyBatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
